# Imagen base de MySQL
FROM mysql:8.0

# Variables de entorno para inicializar la BD
ENV MYSQL_DATABASE=symphony_db
ENV MYSQL_ROOT_PASSWORD=Admin1234*

# No copiamos ningún .sql porque no queremos que se ejecute automáticamente
# COPY mysql-symphony/symphony_db.sql /docker-entrypoint-initdb.d/

# Exponer el puerto estándar
EXPOSE 3307